
---
# tasks file for db_mariadb

- name: Install MariaDB
  ansible.builtin.command: emerge --autounmask-continue --ask=n mariadb
  args:
    creates: /usr/sbin/mysqld  # Avoids reinstallation
  become: yes

- name: Enable MariaDB service at boot (OpenRC)
  ansible.builtin.command: rc-update add mysql default
  args:
    creates: /etc/runlevels/default/mysql
  become: yes

- name: Initialize MariaDB data directory
  ansible.builtin.command: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  args:
    creates: /var/lib/mysql/mysql
  become: yes

- name: Start MariaDB service
  ansible.builtin.service:
    name: mysql
    state: started
  become: yes

