#SPDX-License-Identifier: MIT-0
---
# tasks file for db_postgresql

- name: Install PostgreSQL
  package:
    name: postgresql
    state: present

- name: Start and enable PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes
