# SPDX-License-Identifier: MIT-0
---
# tasks file for webserver_nginx

- name: Gather system facts
  ansible.builtin.setup:

- name: Install NGINX
  ansible.builtin.command: emerge --autounmask-continue --ask=n nginx
  args:
    creates: /usr/sbin/nginx
  become: yes

- name: Ensure NGINX service is enabled
  ansible.builtin.service:
    name: nginx
    enabled: yes
  become: yes

- name: Ensure NGINX web root exists
  ansible.builtin.file:
    path: /var/www/localhost/htdocs
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Ensure images directory exists
  ansible.builtin.file:
    path: /var/www/localhost/htdocs/images
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Copy server icon image to nginx web root
  ansible.builtin.copy:
    src: server.png
    dest: /var/www/localhost/htdocs/images/nginx.png
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Update nginx.conf to listen on all interfaces
  ansible.builtin.replace:
    path: /etc/nginx/nginx.conf
    regexp: 'listen\s+127\.0\.0\.1\s*;'
    replace: 'listen 80;'
  become: yes
  notify: Restart nginx

- name: Deploy server info to index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/localhost/htdocs/index.html
    mode: '0644'
  become: yes

